version: "3.2"

volumes:
  trquake_postgres: {}

services:
  database:
    image: postgres:15.1
    container_name: trquake-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=debug
      - POSTGRES_USER=debug
      - POSTGRES_DB=debug
    volumes:
      - trquake_postgres:/var/lib/postgresql/data

  django:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - PGPASSWORD=debug
      - PGUSER=debug
      - PGDATABASE=debug
      - PGHOST=trquake-database
      - PGPORT=5432
    command:
      - /start-django